import { WaterSourceLocationEntry } from "@/types";

export const entries: WaterSourceLocationEntry[] = [
    {
        id: '1',
        title: 'San Francisco',
        description: 'Description for San Francisco',
        latitude: 37.7749,
        longitude: -122.4194,
        latitudeDelta: 0.0922,
        longitudeDelta: 0.0421,
        images: [],
        upVotes: 0,
        downVotes: 0,
    },
    {
        id: '2',
        title: 'Los Angeles',
        description: 'Description for Los Angeles',
        latitude: 34.0522,
        longitude: -118.2437,
        latitudeDelta: 0.0922,
        longitudeDelta: 0.0421,
        images: [],
        upVotes: 0,
        downVotes: 0,
    },
    {
        id: '3',
        title: 'New York',
        description: 'Description for New York',
        latitude: 40.7128,
        longitude: -74.0060,
        latitudeDelta: 0.0922,
        longitudeDelta: 0.0421,
        images: [],
        upVotes: 0,
        downVotes: 0,
    },
    {
        id: '4',
        title: 'Chicago',
        description: 'Description for Chicago',
        latitude: 41.8781,
        longitude: -87.6298,
        latitudeDelta: 0.0922,
        longitudeDelta: 0.0421,
        images: [],
        upVotes: 0,
        downVotes: 0,
    },
    {
        id: '5',
        title: 'Houston',
        description: 'Description for Houston',
        latitude: 29.7604,
        longitude: -95.3698,
        latitudeDelta: 0.0922,
        longitudeDelta: 0.0421,
        images: [],
        upVotes: 0,
        downVotes: 0,
    }
];